In [2]:
import pandas as pd
import numpy as np

### Importación de datos

In [3]:
covariables_df = pd.read_csv("sourceData/covariables_sv.csv", dtype={'especievalida':str, 'min':str, 'max':str, 'ET_ID':int})[7407:]
covariables_df = covariables_df[['especievalida', 'ET_ID']]
covariables_df

                                           especievalida  ET_ID
7407   Politic07.p00 Sembrando vida subsidy 2019  are...  15030
7408   Politic07.p00 Sembrando vida subsidy 2019  are...  15069
7409   Politic07.p00 Sembrando vida subsidy 2019  are...  20103
7410   Politic07.p00 Sembrando vida subsidy 2019  are...  20157
7411   Politic07.p00 Sembrando vida subsidy 2019  are...  20215
...                                                  ...    ...
22216  Politic12.p03 Sembrando vida subsidy 2019 2020...  23004
22217  Politic12.p02 Sembrando vida subsidy 2019 2020...   4006
22218  Politic12.p07 Sembrando vida subsidy 2019 2020...   7059
22219  Politic12.p03 Sembrando vida subsidy 2019 2020...  23002
22220  Politic12.p04 Sembrando vida subsidy 2019 2020...   4010

[14814 rows x 2 columns]

Separando cada variable en diferentes `DataFrames`, desde *Politic07...* hasta *Politic12...*

In [4]:
num_variables: int = int(covariables_df.shape[0] / 2469) # 2469 muncs per variable

variables_dfs = np.empty(num_variables, dtype=pd.DataFrame)
for i in range(num_variables):
    variables_dfs[i] = (covariables_df[['especievalida', 'ET_ID']][i * 2469: (i + 1) * 2469])

for i in range(num_variables):
    print(variables_dfs[i]['especievalida'], ': ', variables_dfs[i].shape)

7407    Politic07.p00 Sembrando vida subsidy 2019  are...
7408    Politic07.p00 Sembrando vida subsidy 2019  are...
7409    Politic07.p00 Sembrando vida subsidy 2019  are...
7410    Politic07.p00 Sembrando vida subsidy 2019  are...
7411    Politic07.p00 Sembrando vida subsidy 2019  are...
                              ...
9871    Politic07.p03 Sembrando vida subsidy 2019  are...
9872    Politic07.p00 Sembrando vida subsidy 2019  are...
9873    Politic07.p08 Sembrando vida subsidy 2019  are...
9874    Politic07.p03 Sembrando vida subsidy 2019  are...
9875    Politic07.p04 Sembrando vida subsidy 2019  are...
Name: especievalida, Length: 2469, dtype: object :  (2469, 2)
9876     Politic08.p00 Sembrando vida subsidy 2020area ...
9877     Politic08.p00 Sembrando vida subsidy 2020area ...
9878     Politic08.p00 Sembrando vida subsidy 2020area ...
9879     Politic08.p00 Sembrando vida subsidy 2020area ...
9880     Politic08.p07 Sembrando vida subsidy 2020area ...
                               ...
12340    Politic08.p03 Sembrando vida subsidy 2020area ...
12341    Politic08.p03 Sembrando vida subsidy 2020area ...
12342    Politic08.p09 Sembrando vida subsidy 2020area ...
12343    Politic08.p03 Sembrando vida subsidy 2020area ...
12344    Politic08.p04 Sembrando vida subsidy 2020area ...
Name: especievalida, Length: 2469, dtype: object :  (2469, 2)
12345    Politic09.p00 Sembrando vida subsidy 2019-2020...
12346    Politic09.p00 Sembrando vida subsidy 2019-2020...
12347    Politic09.p00 Sembrando vida subsidy 2019-2020...
12348    Politic09.p00 Sembrando vida subsidy 2019-2020...
12349    Politic09.p06 Sembrando vida subsidy 2019-2020...
                               ...
14809    Politic09.p03 Sembrando vida subsidy 2019-2020...
14810    Politic09.p03 Sembrando vida subsidy 2019-2020...
14811    Politic09.p09 Sembrando vida subsidy 2019-2020...
14812    Politic09.p03 Sembrando vida subsidy 2019-2020...
14813    Politic09.p06 Sembrando vida subsidy 2019-2020...
Name: especievalida, Length: 2469, dtype: object :  (2469, 2)
14814    Politic10.p00 Sembrando vida subsidy 2019area ...
14815    Politic10.p00 Sembrando vida subsidy 2019area ...
14816    Politic10.p00 Sembrando vida subsidy 2019area ...
14817    Politic10.p00 Sembrando vida subsidy 2019area ...
14818    Politic10.p00 Sembrando vida subsidy 2019area ...
                               ...
17278    Politic10.p02 Sembrando vida subsidy 2019area ...
17279    Politic10.p00 Sembrando vida subsidy 2019area ...
17280    Politic10.p05 Sembrando vida subsidy 2019area ...
17281    Politic10.p02 Sembrando vida subsidy 2019area ...
17282    Politic10.p03 Sembrando vida subsidy 2019area ...
Name: especievalida, Length: 2469, dtype: object :  (2469, 2)
17283    Politic11.p00 Sembrando vida subsidy 2020area ...
17284    Politic11.p00 Sembrando vida subsidy 2020area ...
17285    Politic11.p00 Sembrando vida subsidy 2020area ...
17286    Politic11.p00 Sembrando vida subsidy 2020area ...
17287    Politic11.p00 Sembrando vida subsidy 2020area ...
                               ...
19747    Politic11.p03 Sembrando vida subsidy 2020area ...
19748    Politic11.p02 Sembrando vida subsidy 2020area ...
19749    Politic11.p06 Sembrando vida subsidy 2020area ...
19750    Politic11.p02 Sembrando vida subsidy 2020area ...
19751    Politic11.p03 Sembrando vida subsidy 2020area ...
Name: especievalida, Length: 2469, dtype: object :  (2469, 2)
19752    Politic12.p00 Sembrando vida subsidy 2019 2020...
19753    Politic12.p00 Sembrando vida subsidy 2019 2020...
19754    Politic12.p00 Sembrando vida subsidy 2019 2020...
19755    Politic12.p00 Sembrando vida subsidy 2019 2020...
19756    Politic12.p00 Sembrando vida subsidy 2019 2020...
                               ...
22216    Politic12.p03 Sembrando vida subsidy 2019 2020...
22217    Politic12.p02 Sembrando vida subsidy 2019 2020...
22218    Politic12.p07 Sembrando vida subsidy 2019 2020...
22219    Politic12.p03 Sembrando vida subsidy 2019 2020...
22220    Politic12.p04 Sembrando vida subsidy 2019 2020...
Name: especievalida, Length: 2469, dtype: object :  (2469, 2)

Por último, de cada `DataFrame` se agrupan las celdas con la misma covariable.

In [5]:
def group_by_var(df: pd.DataFrame, variables: str, values: str):
    names = []
    cells = []
    for v in set(df[variables]):
        names.append(v)
        cells.append(df[df[variables]==v][values].tolist())

    return pd.DataFrame({'name':names, 'cells':cells})

In [6]:
Politic07_df = group_by_var(variables_dfs[0], 'especievalida', 'ET_ID')
Politic07_df

,name,cells
0,Politic07.p10 Sembrando vida subsidy 2019 are...,"[30041, 30194, 30064, 21029, 30018, 30098, 300..."
1,Politic07.p03 Sembrando vida subsidy 2019 are...,"[9017, 10006, 30028, 21173, 10031, 30138, 3011..."
2,Politic07.p06 Sembrando vida subsidy 2019 are...,"[21211, 21080, 7035, 21101, 30068, 30116, 3014..."
3,Politic07.p01 Sembrando vida subsidy 2019 are...,"[8037, 8005, 10007, 8004, 8045, 8032, 2002, 10..."
4,Politic07.p09 Sembrando vida subsidy 2019 are...,"[30030, 21216, 21210, 30062, 21192, 30103, 300..."
5,Politic07.p08 Sembrando vida subsidy 2019 are...,"[30120, 30199, 30007, 21084, 21123, 30117, 300..."
6,Politic07.p00 Sembrando vida subsidy 2019 are...,"[15030, 15069, 20103, 20157, 20215, 20389, 203..."
7,Politic07.p07 Sembrando vida subsidy 2019 are...,"[7055, 30186, 30052, 30196, 21204, 30100, 2107..."
8,Politic07.p05 Sembrando vida subsidy 2019 are...,"[10029, 30119, 30131, 10016, 21044, 30179, 300..."
9,Politic07.p04 Sembrando vida subsidy 2019 are...,"[10027, 10030, 30176, 30053, 30054, 30126, 100..."
10,Politic07.p02 Sembrando vida subsidy 2019 are...,"[21034, 9006, 21119, 19046, 9002, 15122, 15024..."

In [7]:
Politic08_df = group_by_var(variables_dfs[1], 'especievalida', 'ET_ID')
Politic08_df

,name,cells
0,Politic08.p02 Sembrando vida subsidy 2020area ...,"[9017, 9002, 21126, 15024, 15070, 20385, 29005..."
1,Politic08.p07 Sembrando vida subsidy 2020area ...,"[20215, 21181, 20224, 21102, 20256, 20456, 205..."
2,Politic08.p00 Sembrando vida subsidy 2020area ...,"[15030, 15069, 20103, 20157, 20389, 20393, 210..."
3,Politic08.p08 Sembrando vida subsidy 2020area ...,"[29008, 20106, 20493, 17003, 21132, 20547, 211..."
4,Politic08.p06 Sembrando vida subsidy 2020area ...,"[10029, 20144, 21148, 20140, 21153, 17010, 204..."
5,Politic08.p01 Sembrando vida subsidy 2020area ...,"[15058, 21119, 8037, 26055, 21140, 9011, 10007..."
6,Politic08.p05 Sembrando vida subsidy 2020area ...,"[21146, 20047, 20283, 17002, 10038, 24022, 201..."
7,Politic08.p04 Sembrando vida subsidy 2020area ...,"[20054, 10027, 20286, 10031, 21164, 20248, 170..."
8,Politic08.p10 Sembrando vida subsidy 2020area ...,"[29035, 20303, 30120, 20352, 20025, 17032, 300..."
9,Politic08.p09 Sembrando vida subsidy 2020area ...,"[20556, 29016, 29039, 17033, 20250, 29047, 290..."
10,Politic08.p03 Sembrando vida subsidy 2020area ...,"[10006, 10028, 10030, 8064, 8022, 20523, 10024..."

In [8]:
Politic09_df = group_by_var(variables_dfs[2], 'especievalida', 'ET_ID')
Politic09_df

,name,cells
0,Politic09.p05 Sembrando vida subsidy 2019-2020...,"[21146, 21148, 10027, 21153, 17010, 20422, 211..."
1,Politic09.p01 Sembrando vida subsidy 2019-2020...,"[15058, 8037, 19046, 8005, 26055, 21140, 10007..."
2,Politic09.p04 Sembrando vida subsidy 2019-2020...,"[20054, 20047, 10006, 17002, 21173, 10030, 202..."
3,Politic09.p07 Sembrando vida subsidy 2019-2020...,"[10029, 20224, 21102, 20521, 21132, 20564, 170..."
4,Politic09.p02 Sembrando vida subsidy 2019-2020...,"[21034, 9006, 21119, 9017, 9002, 15122, 21126,..."
5,Politic09.p03 Sembrando vida subsidy 2019-2020...,"[10028, 30028, 8064, 8022, 20523, 30138, 30118..."
6,Politic09.p10 Sembrando vida subsidy 2019-2020...,"[20303, 30120, 20352, 30041, 30194, 30064, 210..."
7,Politic09.p00 Sembrando vida subsidy 2019-2020...,"[15030, 15069, 20103, 20157, 20389, 20393, 210..."
8,Politic09.p09 Sembrando vida subsidy 2019-2020...,"[20556, 17033, 29035, 29052, 7055, 20383, 2121..."
9,Politic09.p08 Sembrando vida subsidy 2019-2020...,"[29008, 20106, 20493, 29016, 29039, 20250, 170..."
10,Politic09.p06 Sembrando vida subsidy 2019-2020...,"[20215, 21181, 20144, 20256, 20456, 20518, 290..."

In [9]:
Politic10_df = group_by_var(variables_dfs[3], 'especievalida', 'ET_ID')
Politic10_df

,name,cells
0,Politic10.p00 Sembrando vida subsidy 2019area ...,"[15030, 15069, 20103, 20157, 20215, 20389, 203..."
1,Politic10.p03 Sembrando vida subsidy 2019area ...,"[8045, 19025, 21173, 9016, 10038, 30138, 30118..."
2,Politic10.p04 Sembrando vida subsidy 2019area ...,"[8004, 9007, 30028, 21080, 30208, 21114, 30053..."
3,Politic10.p10 Sembrando vida subsidy 2019area ...,"[21034, 9006, 21119, 8037, 9017, 10029, 10027,..."
4,Politic10.p05 Sembrando vida subsidy 2019area ...,"[19046, 15024, 9011, 15070, 21101, 21204, 3006..."
5,Politic10.p01 Sembrando vida subsidy 2019 are...,"[20490, 2002, 9010, 30139, 30016, 5035, 30211,..."
6,Politic10.p07 Sembrando vida subsidy 2019area ...,"[9002, 30199, 30131, 30052, 21210, 30116, 3002..."
7,Politic10.p06 Sembrando vida subsidy 2019area ...,"[8005, 15122, 10007, 30186, 30176, 21084, 3014..."
8,Politic10.p02 Sembrando vida subsidy 2019area ...,"[8032, 15020, 30026, 30146, 30191, 7113, 30140..."
9,Politic10.p09 Sembrando vida subsidy 2019area ...,"[7055, 21211, 7035, 30196, 21088, 30037, 30137..."
10,Politic10.p08 Sembrando vida subsidy 2019area ...,"[30119, 30041, 30098, 30030, 21216, 30113, 300..."

In [10]:
Politic11_df = group_by_var(variables_dfs[4], 'especievalida', 'ET_ID')
Politic11_df

,name,cells
0,Politic11.p04 Sembrando vida subsidy 2020area ...,"[20341, 24001, 30131, 20541, 20471, 29028, 210..."
1,Politic11.p00 Sembrando vida subsidy 2020area ...,"[15030, 15069, 20103, 20157, 20215, 20389, 203..."
2,Politic11.p09 Sembrando vida subsidy 2020area ...,"[9017, 17006, 20518, 29017, 20140, 20422, 2011..."
3,Politic11.p08 Sembrando vida subsidy 2020area ...,"[21119, 8037, 21126, 20047, 20286, 20246, 2012..."
4,Politic11.p07 Sembrando vida subsidy 2020area ...,"[15058, 20281, 20523, 20332, 20248, 20093, 301..."
5,Politic11.p02 Sembrando vida subsidy 2020area ...,"[26055, 21140, 8004, 28009, 9007, 8045, 19025,..."
6,Politic11.p10 Sembrando vida subsidy 2020area ...,"[29008, 21181, 21146, 10029, 20106, 20144, 204..."
7,Politic11.p06 Sembrando vida subsidy 2020area ...,"[20195, 17027, 20164, 20196, 21026, 21023, 211..."
8,Politic11.p03 Sembrando vida subsidy 2020area ...,"[15024, 9011, 15070, 10007, 20385, 29005, 3002..."
9,Politic11.p01 Sembrando vida subsidy 2020 are...,"[9005, 15109, 21166, 20444, 15033, 15020, 1308..."
10,Politic11.p05 Sembrando vida subsidy 2020area ...,"[9002, 21080, 21030, 20230, 21028, 20346, 2033..."

In [11]:
Politic12_df = group_by_var(variables_dfs[5], 'especievalida', 'ET_ID')
Politic12_df

,name,cells
0,Politic12.p09 Sembrando vida subsidy 2019 2020...,"[20054, 20303, 20422, 20147, 20464, 20308, 203..."
1,Politic12.p04 Sembrando vida subsidy 2019 2020...,"[8004, 9007, 21173, 20341, 21030, 24001, 30190..."
2,Politic12.p07 Sembrando vida subsidy 2019 2020...,"[21126, 20281, 20286, 20246, 20332, 20248, 200..."
3,Politic12.p03 Sembrando vida subsidy 2019 2020...,"[20385, 29005, 8045, 19025, 9016, 30138, 30118..."
4,Politic12.p08 Sembrando vida subsidy 2019 2020...,"[9002, 17006, 20518, 29017, 20140, 20047, 2011..."
5,Politic12.p06 Sembrando vida subsidy 2019 2020...,"[15058, 8005, 15122, 15024, 10007, 20523, 2019..."
6,Politic12.p02 Sembrando vida subsidy 2019 2020...,"[26055, 21140, 28009, 8032, 24056, 21063, 1702..."
7,Politic12.p01 Sembrando vida subsidy 2019 2020...,"[9003, 29043, 9005, 15109, 21166, 20444, 20490..."
8,Politic12.p05 Sembrando vida subsidy 2019 2020...,"[19046, 9011, 15070, 30028, 17027, 20164, 2023..."
9,Politic12.p10 Sembrando vida subsidy 2019 2020...,"[21034, 29008, 9006, 21119, 8037, 21181, 9017,..."
10,Politic12.p00 Sembrando vida subsidy 2019 2020...,"[15030, 15069, 20103, 20157, 20215, 20389, 203..."

### Almacenamiento de los datos en JSON

In [ ]:
## Politic07_df.to_json('generatedData/forestal/politic07.json', orient='records', index=False)
## Politic08_df.to_json('generatedData/forestal/politic08.json', orient='records', index=False)
## Politic09_df.to_json('generatedData/forestal/politic09.json', orient='records', index=False)
## Politic10_df.to_json('generatedData/forestal/politic10.json', orient='records', index=False)
## Politic11_df.to_json('generatedData/forestal/politic11.json', orient='records', index=False)
## Politic12_df.to_json('generatedData/forestal/politic12.json', orient='records', index=False)